// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystemPrototype.API.Data;


#nullable disable

namespace TicketSystemPrototype.API.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20250323135151_RenamedAssignedToPropertyInTicket")]
    partial class RenamedAssignedToPropertyInTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("TicketSystemPrototype.Objects.ActionTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("ActionTracks");
                });

            modelBuilder.Entity("TicketSystemPrototype.Objects.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Robin",
                            CreatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Robin",
                            Description = "Read Tutorials and make a project",
                            Name = "Learn Blazor",
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Robin",
                            CreatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Robin",
                            Description = "Download EFCore NuGet Package and configure",
                            Name = "Implement Entity Framework Core",
                            Priority = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Robin",
                            CreatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Robin",
                            Description = "Download SQLite Browser and open generated Datebase file",
                            Name = "Implement SQLite Database with SQLite Browser",
                            Priority = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("TicketSystemPrototype.Objects.ActionTrack", b =>
                {
                    b.HasOne("TicketSystemPrototype.Objects.Ticket", "Ticket")
                        .WithMany("ActionTracks")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketSystemPrototype.Objects.Ticket", b =>
                {
                    b.Navigation("ActionTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
