// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystemPrototype.Data;

#nullable disable

namespace TicketSystemPrototype.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("TicketSystemPrototype.Objects.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssingedTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssingedTo = "Robin",
                            CreatedAt = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "Robin",
                            Description = "Read Tutorials and make a project",
                            Name = "Learn Blazor",
                            Priority = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AssingedTo = "Robin",
                            CreatedAt = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "Robin",
                            Description = "Download EFCore NuGet Package and configure",
                            Name = "Implement Entity Framework Core",
                            Priority = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AssingedTo = "Robin",
                            CreatedAt = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "Robin",
                            Description = "Download SQLite Browser and open generated Datebase file",
                            Name = "Implement SQLite Database with SQLite Browser",
                            Priority = 1,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
